### ISSUE TITLE
KIP overlay text is not aligned

### ISSUE THREAD

**Issue by 0zAND1z** [KIPFoundation/kip.foundation#7]
![image](https://user-images.githubusercontent.com/11145839/66658243-b4729580-ec5e-11e9-81dc-ae460b62f6c3.png)

Please align the KIP text to center and middle.

It looks like KIP text is aligned to lower right.

**Comment by chuckle-architect** [comment]
Bug fixed , here is the [commit](https://github.com/KIPFoundation/kip.foundation/commit/2bb76b731e03b43a6729e59edbbaa7fd991d4697)
