### ISSUE TITLE
Menu item selected is going dark

### ISSUE THREAD

**Issue by 0zAND1z** [KIPFoundation/kip.foundation#8]
![image](https://user-images.githubusercontent.com/11145839/66658657-8c376680-ec5f-11e9-859b-6d98c37be9d5.png)
Menu item is turning black/transparent and invisible when active. Please fix this in the CSS.

**Comment by chuckle-architect** [comment]
Bug Fixed , here is the [commit](https://github.com/KIPFoundation/kip.foundation/commit/2ffadaf03c5771018e08b78e515970e2ee6cdd7c)
